---
"Type: Core":
  - changed-files:
      - any-glob-to-any-file: "qa_framework/**/*"

"Type: Documentation":
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "*.md"

"Type: CI/CD":
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**/*"

"Type: Tests":
  - changed-files:
      - any-glob-to-any-file: "tests/**/*"
