name: Semantic Release
on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Python Auto-Release
        uses: carlos-camara/qa-hub-actions/python-auto-release@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
